# Generated by Django 3.1.7 on 2021-07-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='howManylikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postliked', to='network.post')),
                ('userliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='userliked',
            field=models.ManyToManyField(through='network.Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
