# Generated by Django 3.1.7 on 2021-08-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210727_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
