# Generated by Django 3.1.7 on 2021-06-11 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_postuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following1',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
