# Generated by Django 3.1.7 on 2021-08-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editMode',
            field=models.IntegerField(default=False),
        ),
    ]
