# Generated by Django 3.1.7 on 2021-08-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210816_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userHimself',
            field=models.BooleanField(default=False),
        ),
    ]
