# Generated by Django 3.1.7 on 2021-08-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_userhimself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userHimself',
            field=models.BooleanField(default=True),
        ),
    ]
