# Generated by Django 3.1.7 on 2021-08-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210818_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userHimself',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
